// Theme Request
export const SET_APPEARANCE = 'SET_APPEARANCE';
export const SET_PRIMARY_COLOR = 'SET_PRIMARY_COLOR';
export const RESET_THEME = 'RESET_THEME';

// Login Request
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

//Device Request
export const DEVICE_CONFIGURE_STARTUP = 'DEVICE_CONFIGURE_STARTUP';
export const DEVICE_REQUEST_SCAN = 'DEVICE_REQUEST_SCAN';
export const DEVICE_REQUEST_REMOVE_ALL = 'DEVICE_REQUEST_REMOVE_ALL';
export const DEVICE_REQUEST_REFRESH_DEVICE_INFO = 'DEVICE_REQUEST_REFRESH_DEVICE_INFO';
export const DEVICE_REQUEST_SELECT_DEVICE = 'DEVICE_REQUEST_SELECT_DEVICE';
export const DEVICE_REQUEST_REMOVE_SELECTED_DEVICE = 'DEVICE_REQUEST_REMOVE_SELECTED_DEVICE';

//Device Response
export const ON_FETCH_DEVICE_INFO = 'ON_FETCH_DEVICE_INFO';
export const ON_ERROR_FETCH_DEVICE_INFO = 'ON_ERROR_FETCH_DEVICE_INFO';
export const ON_REFRESH_DEVICE_INFO = 'ON_REFRESH_DEVICE_INFO';
export const ON_NEW_DEVICE_FOUND = 'ON_NEW_DEVICE_FOUND';
export const ON_DEVICE_SCAN_FINISH = 'ON_DEVICE_SCAN_FINISH';

//App Config
export const SET_APP_CONFIG_PATH = 'SET_APP_CONFIG_PATH';
export const SET_APP_CONFIG_PORT = 'SET_APP_CONFIG_PORT';
export const SET_APP_CONFIG_REFRESH_INTERVAL = 'SET_APP_CONFIG_REFRESH_INTERVAL';
export const SET_APP_CONFIG_RESTORE_DEFAULT = 'SET_APP_CONFIG_RESTORE_DEFAULT';
